[package]
name = "rose-algebra"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "algebra_vector"
harness = false

[dependencies]

[dev-dependencies]
criterion = { version = "*", features = ["html_reports"] }